// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqougddjdmlpemvtlwmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlxb3VnZGRqZG1scGVtdnRsd21jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzk1MDMsImV4cCI6MjA2MDgxNTUwM30.RW7BtQcHPoLVjwv6gqfgN-FiI2tSsYtdYPfQRZOpDUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);